### ISSUE TITLE
Determine when the user is at the last track instead of naively waiting for X seconds

### ISSUE THREAD

**Issue by goibon** [StefanMich/SpotifyRandomAlbum#8]
The current implementation sleeps for X seconds where X is the duration of the album before queuing the next album. This assumes that the user listens to the entire album without any interruptions.
Since the [Player API](https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-the-users-currently-playing-track) returns the id (and even number on the album), the duration and the progress (in ms), this would be a more accurate way of determining when it would be a good time to find a new album to add to the queue.

This of course still depends on the user listening to the last song of the album so not completely bulletproof if we have no way of determining what's left in the users queue.

**Comment by StefanMich** [comment]
Player does not autoplay anymore, closing
